# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.0.26
_src_path: https://github.com/clearskies-py/clearskies-module-template
author_email: cmancone@gmail.com
author_name: Conor Mancone
create_backends: false
create_columns: false
create_configs: false
create_endpoints: true
create_models: false
module_display_name: Akeyless Custom Producer
module_name: akeyless-custom-producer
